name: Pull Request Pipeline

on:
  pull_requests:
  types: [opened, syncronize, ready_for_review]
  branches:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/actions/setup-dotnet
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
          cache: true
      - name: Install Nuget packages
        run: dotnet restore --locked-mode
      # - run: dotnet build GateAdventures
