name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
          cache: true
      - name: Install Nuget packages
        run: dotnet restore --locked-mode
      - name: Build Project
        run: dotnet build
